// export const data = [
//   { id: 1, status: 're-exam', name: 'Rakhimjonov Davronbek' },
//   { id: 2, status: 'passed', name: 'Komil Muhammadiyev' },
//   { id: 3, status: 're-exam', name: 'Mahkamov Tohirbek' },
//   { id: 4, status: 'failed', name: 'Nuraliev Zuhriddin' },
//   { id: 5, status: 're-exam', name: 'Dilshodbek Boymamatov' },
//   { id: 6, status: 'passed', name: 'Muhharam Ozodboyeva' },
//   { id: 7, status: 'failed', name: 'Azimov Umarbek' },
//   { id: 8, status: 're-exam', name: 'Abdurazzaqov Hasanboy' },
//   { id: 9, status: 'passed', name: 'Davlyatov MuhammadAli' },
//   { id: 10, status: 'failed', name: 'Zohidova Ruqiya' },
//   { id: 11, status: 'passed', name: 'Abduhamidov Nurbek' },
//   { id: 12, status: 'failed', name: 'Nizamov Sardorbek' },
// ];

export const data = [
  { id: 1, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'TerDu', job: 'Developer' },
  { id: 2, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'GulDu', job: 'Developer' },
  { id: 3, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'QarDu', job: 'Developer' },
  { id: 4, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'NamDu', job: 'Developer' },
  { id: 5, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'TATU', job: 'Developer' },
  { id: 6, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'UrDu', job: 'Developer' },
  { id: 7, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'ADU', job: 'Developer' },
  { id: 8, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'TDYU', job: 'Developer' },
  { id: 9, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'BuxDu', job: 'Developer' },
  { id: 10, name: 'Ruqiya', age: 18, address: 'Fergana', status: 'St', nickname: '@bir_nma', univ: 'FarDu', job: 'Developer' },
  { id: 11, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'TDYU', job: 'Developer' },
  { id: 12, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 13, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 14, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 15, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 16, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 17, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 18, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 19, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
  { id: 20, name: 'Ruqiya', age: 18, address: 'Fargona', status: 'St', nickname: '@bir_nma', univ: 'JizDu', job: 'Developer' },
]